name: clean_architecture_sample
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+01

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  sqflite: ^2.3.0
  dio: ^5.9.0
  connectivity_plus: ^5.0.0
  path: ^1.8.3
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  equatable: ^2.1.0
  bloc_test: ^9.1.7
  firebase_core: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  injectable_generator: ^2.4.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true
