// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKPmK0PTcE3DDsnLfocD8qhnO6wc3p7c',
    appId: '1:577110800760:web:9d817be102f7e27d93f08d',
    messagingSenderId: '577110800760',
    projectId: 'matrix-6371e',
    authDomain: 'matrix-6371e.firebaseapp.com',
    storageBucket: 'matrix-6371e.firebasestorage.app',
    measurementId: 'G-39FFJCQDTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHGH2s8nYZt37NtLoypD7kRKvcYVGVs64',
    appId: '1:577110800760:android:569399451e648ab493f08d',
    messagingSenderId: '577110800760',
    projectId: 'matrix-6371e',
    storageBucket: 'matrix-6371e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG972wqYZz9GzTWlPxB2DZUxW3pi-QdfM',
    appId: '1:577110800760:ios:1e855d65d0e2dd9e93f08d',
    messagingSenderId: '577110800760',
    projectId: 'matrix-6371e',
    storageBucket: 'matrix-6371e.firebasestorage.app',
    iosClientId: '577110800760-0ojcb1s07b1bba37g357rb5u961o004k.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchitectureSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG972wqYZz9GzTWlPxB2DZUxW3pi-QdfM',
    appId: '1:577110800760:ios:1e855d65d0e2dd9e93f08d',
    messagingSenderId: '577110800760',
    projectId: 'matrix-6371e',
    storageBucket: 'matrix-6371e.firebasestorage.app',
    iosClientId: '577110800760-0ojcb1s07b1bba37g357rb5u961o004k.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchitectureSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzKPmK0PTcE3DDsnLfocD8qhnO6wc3p7c',
    appId: '1:577110800760:web:e6bb10406d26808193f08d',
    messagingSenderId: '577110800760',
    projectId: 'matrix-6371e',
    authDomain: 'matrix-6371e.firebaseapp.com',
    storageBucket: 'matrix-6371e.firebasestorage.app',
    measurementId: 'G-BCJQ77CQ1G',
  );
}
